# Generated by Django 2.2.12 on 2020-05-13 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200513_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='prn_number',
            new_name='prn_numbers',
        ),
    ]
