# Generated by Django 2.2.12 on 2020-05-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200513_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='reason',
            field=models.CharField(default='Regular Attendance', max_length=200),
        ),
    ]
