# Generated by Django 2.2.12 on 2020-05-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200514_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prn_number',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
