# Generated by Django 2.2.12 on 2020-05-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200514_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/pp.jpg', upload_to='profile_picture'),
        ),
    ]
