# Generated by Django 2.2.12 on 2020-05-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20200515_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='pp.jpg', upload_to='profile_picture/teacher'),
        ),
    ]
